port:                          4567
proxy: 
api_key:                       
secret_key:                    
tokens_file:                   tokens

transactions_file:             transactions
subscriptions_file:          subscriptions
notifications_file:          notifications

recent_transactions_stored:    5
recent_notifications_stored:   5
notary_app_view_payload_url:   http://localhost:4567/notary
payment_redirect_url:          http://localhost:4567/returnTransaction
subscription_redirect_url:     http://localhost:4567/callbackSubscription
FQDN:                          https://api.att.com
listener_url:                  http://localhost:4567/transactionListener
listener_url:                  http://localhost:4567/subscriptionListener
notifications_url:             http://localhost:4567

min_transaction_value: 0.00
max_transaction_value: 2.99

min_subscription_value: 0.00
max_subscription_value: 3.99

help_link: #
source_link: #
download_link: #
