
# Licensed by AT&T under 'Software Development Kit Tools Agreement.' 2013
# TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION: http://developer.att.com/sdk_agreement/
# Copyright 2013 AT&T Intellectual Property. All rights reserved. http://developer.att.com
# For more information contact developer.support@att.com

port:             4567
proxy: 
api_key:          
secret_key:       
FQDN:             https://api.att.com
redirect_url:     http://localhost:4567/

help_link: #
download_link: #
source_link: #
